-- ==========================================
-- SUPABASE / POSTGRESQL DATABASE SETUP SCRIPT
-- For absensi18studio-app (Lapanbelas.id Attendance App)
-- Run this script in your Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- ==========================================

-- 1. Create table 'karyawan' if not exists
CREATE TABLE IF NOT EXISTS public.karyawan (
    email TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    nama TEXT NOT NULL,
    jabatan TEXT NOT NULL,
    gaji_pokok NUMERIC DEFAULT 3000000,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MIGRATION: Ensure 'gaji_pokok' exists in 'karyawan' in case the table already existed
ALTER TABLE public.karyawan ADD COLUMN IF NOT EXISTS gaji_pokok NUMERIC DEFAULT 3000000;

-- 2. Create table 'office_config' (Geofence settings) if not exists
CREATE TABLE IF NOT EXISTS public.office_config (
    id BIGINT PRIMARY KEY,
    lat NUMERIC NOT NULL,
    lon NUMERIC NOT NULL,
    radius INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MIGRATION: Ensure all columns exist in 'office_config' in case the table already existed
ALTER TABLE public.office_config ADD COLUMN IF NOT EXISTS lat NUMERIC;
ALTER TABLE public.office_config ADD COLUMN IF NOT EXISTS lon NUMERIC;
ALTER TABLE public.office_config ADD COLUMN IF NOT EXISTS radius INTEGER;

-- 3. Create table 'izin_requests' (Leave applications) if not exists
CREATE TABLE IF NOT EXISTS public.izin_requests (
    id TEXT PRIMARY KEY,
    nama TEXT NOT NULL,
    jenis TEXT NOT NULL,
    tgl TEXT NOT NULL,
    alasan TEXT NOT NULL,
    status TEXT NOT NULL,
    karyawan_email TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MIGRATION: Ensure all columns exist in 'izin_requests' in case the table already existed
ALTER TABLE public.izin_requests ADD COLUMN IF NOT EXISTS karyawan_email TEXT;

-- 4. Create table 'absensi_riwayat' (Attendance logs) if not exists
CREATE TABLE IF NOT EXISTS public.absensi_riwayat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tgl TEXT NOT NULL,
    masuk TEXT NOT NULL,
    pulang TEXT,
    status TEXT NOT NULL,
    denda NUMERIC DEFAULT 0,
    lembur NUMERIC DEFAULT 0,
    tipe TEXT NOT NULL,
    karyawan_email TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- MIGRATION: Ensure all columns exist in 'absensi_riwayat' in case the table already existed
ALTER TABLE public.absensi_riwayat ADD COLUMN IF NOT EXISTS denda NUMERIC DEFAULT 0;
ALTER TABLE public.absensi_riwayat ADD COLUMN IF NOT EXISTS lembur NUMERIC DEFAULT 0;
ALTER TABLE public.absensi_riwayat ADD COLUMN IF NOT EXISTS karyawan_email TEXT;

-- 5. Create table 'hari_libur' (Public holidays) if not exists
CREATE TABLE IF NOT EXISTS public.hari_libur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal TEXT NOT NULL UNIQUE,
    keterangan TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) CONFIGURATION
-- ==========================================
-- Disable RLS to allow direct CRUD operations from client-side via Anon Key
ALTER TABLE public.karyawan DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.izin_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.absensi_riwayat DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.hari_libur DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- SEED DEFAULT INITIAL DATA
-- ==========================================

-- Seed default office configuration (Lapanbelas.id Geofence)
INSERT INTO public.office_config (id, lat, lon, radius)
VALUES (1, 4.47604, 97.95755, 800)
ON CONFLICT (id) DO NOTHING;

-- Seed default staff account (Budi Karyawan)
INSERT INTO public.karyawan (email, password, nama, jabatan, gaji_pokok)
VALUES ('budi@lapanbelas.id', 'password123', 'Budi Karyawan', 'Staff Operasional', 3500000)
ON CONFLICT (email) DO NOTHING;

-- Seed default owner account (Owner Bambang)
INSERT INTO public.karyawan (email, password, nama, jabatan, gaji_pokok)
VALUES ('owner@lapanbelas.id', 'password123', 'Bambang Owner', 'Owner', 10000000)
ON CONFLICT (email) DO NOTHING;
